// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMgJBuGvAimqI1gm6ZAL0DyOsm68Sa9G4',
    appId: '1:1052372162545:web:4ae72f035463395d605650',
    messagingSenderId: '1052372162545',
    projectId: 'study-app-d3c52',
    authDomain: 'study-app-d3c52.firebaseapp.com',
    storageBucket: 'study-app-d3c52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKnikklgeVZ5RAsaxUQInvj4HmLcKGLIo',
    appId: '1:1052372162545:android:1f6a93ff7b6bfa47605650',
    messagingSenderId: '1052372162545',
    projectId: 'study-app-d3c52',
    storageBucket: 'study-app-d3c52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1cMYFHcgE6w9Ix4fey8b8c7fE12h6Fm8',
    appId: '1:1052372162545:ios:8aeb3bb3dae14cee605650',
    messagingSenderId: '1052372162545',
    projectId: 'study-app-d3c52',
    storageBucket: 'study-app-d3c52.appspot.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1cMYFHcgE6w9Ix4fey8b8c7fE12h6Fm8',
    appId: '1:1052372162545:ios:c32a4b7c4144652d605650',
    messagingSenderId: '1052372162545',
    projectId: 'study-app-d3c52',
    storageBucket: 'study-app-d3c52.appspot.com',
    iosBundleId: 'com.example.studyApp.RunnerTests',
  );
}
